-- Use the database (make sure CompanyDB is already created)
USE CompanyDB;
GO

-- 1. DEPT Table
CREATE TABLE DEPT (
    DUNM INT PRIMARY KEY,
    SSN INT,
    HIRDATE DATE,
    DN VARCHAR(50)
);

-- 2. EMP Table
CREATE TABLE EMP (
    SSN INT PRIMARY KEY,
    Fname VARCHAR(50),
    Lname VARCHAR(50),
    gender CHAR(1),
    super_id INT NULL,
    BD DATE,
    DUNM INT,
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM),
    FOREIGN KEY (super_id) REFERENCES EMP(SSN)
);

-- 3. LOC Table
CREATE TABLE LOC (
    DUNM INT,
    LOC VARCHAR(100),
    PRIMARY KEY (DUNM, LOC),
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);

-- 4. PROJECT Table
CREATE TABLE PROJECT (
    PNUM INT PRIMARY KEY,
    PN VARCHAR(100),
    LOC VARCHAR(100),
    CITY VARCHAR(100),
    DUNM INT,
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);

-- 5. WORK Table
CREATE TABLE WORK (
    SSN INT,
    PNUM INT,
    hours DECIMAL(5,2),
    PRIMARY KEY (SSN, PNUM),
    FOREIGN KEY (SSN) REFERENCES EMP(SSN),
    FOREIGN KEY (PNUM) REFERENCES PROJECT(PNUM)
);

-- 6. DEPENDENT Table
CREATE TABLE DEPENDENT (
    dnum INT,
    BD DATE,
    GENDER CHAR(1),
    ssn INT,
    FOREIGN KEY (ssn) REFERENCES EMP(SSN)
);
